name: 'Repository Initialization'
description: 'Initialize repository by checking out code and installing dependencies'

inputs:
  WORKING_DIRECTORY:
    description: 'Working directory'
    required: true
  fetch-depth:
    description: 'Number of commits to fetch'
    required: false
    default: '0'

runs:
  using: 'composite'
  steps:
    - name: Init Repository
      shell: bash
      run: ./.github/actions/init/init.sh
      env:
        NX_MAX_WORKERS: 4
