name: 'Repository Initialization'
description: 'Initialize repository by checking out code and installing dependencies'

inputs:
  WORKING_DIRECTORY:
    description: 'The working directory to init the workflow in'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Init Repository
      shell: bash
      run: ${{ github.action_path }}/init.sh ${{ inputs.WORKING_DIRECTORY }}
