name: 'Repository Initialization'
description: 'Initialize repository by checking out code and installing dependencies'

runs:
  using: 'composite'
  steps:

    - name: Init Repository
      shell: bash
      run: ${{ github.action_path }}/init.sh ${{ env.WORKING_DIRECTORY }}
