name: 'Repository Initialization'
description: 'Initialize repository by checking out code and installing dependencies'

runs:
  using: 'composite'
  steps:
    - uses: biznet-io/github-actions/setup-working-directory@v1

    - name: Init Repository
      shell: bash
      run: ${{ github.action_path }}/init.sh ${{ env.WORKING_DIRECTORY }}
