name: 'Setup ASDF Plugins'
description: 'Install and configure any ASDF plugins with specified versions using environment variables'

runs:
  using: 'composite'
  steps:
    - name: Setup ASDF Plugins
      id: setup
      shell: bash
      run: ${{ github.action_path }}/setup-plugins.sh
