name: Simple ASDF Setup Example

# Define your development tools once at the workflow level
env:
  ASDF_PLUGINS: |
    [
      {"name": "deno", "version": "2.3.1"},
      {
        "name": "java", 
        "version": "adoptopenjdk-17.0.14+7",
        "env": {"JAVA_HOME": "{install_path}"}
      },
      {"name": "node", "version": "20.10.0"}
    ]
  ASDF_ADD_TO_PATH: "deno,node"

on: [push, pull_request]

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/setup@v3
      
      - name: Setup Development Tools
        uses: ./setup-asdf-plugins
        # That's it! No configuration needed
      
      - name: Build Frontend
        run: |
          # All your tools are ready to use
          deno --version
          node --version
          
          # Your frontend build commands
          echo "Building frontend with Deno and Node..."

  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/setup@v3
      
      - name: Setup Development Tools
        uses: ./setup-asdf-plugins
        # Same tools, no duplication!
      
      - name: Build Backend
        run: |
          # All your tools are ready to use
          java -version
          echo "JAVA_HOME: $JAVA_HOME"
          
          # Your backend build commands
          echo "Building backend with Java..."

  mobile:
    runs-on: ubuntu-latest
    env:
      # Override tools for this specific job
      ASDF_PLUGINS: |
        [
          {"name": "flutter", "version": "3.16.0"},
          {"name": "java", "version": "adoptopenjdk-17.0.14+7"}
        ]
      ASDF_ADD_TO_PATH: "flutter"
    steps:
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/setup@v3
      
      - name: Setup Mobile Development Tools
        uses: ./setup-asdf-plugins
        # Uses job-specific tools (Flutter + Java)
      
      - name: Build Mobile App
        run: |
          flutter --version
          java -version
          echo "Building mobile app with Flutter..."