name: 'Setup Working Directory'
description: 'Sets up the working directory for the job'

inputs:
  path:
    description: 'Path where the working directory should be created'
    default: ''
    required: false

runs:
  using: 'composite'
  steps:
    - id: set_working_directory
      shell: bash
      run: |
        WORKING_DIRECTORY="${{ inputs.path != '' && inputs.path || env.WORKING_DIRECTORY_PREFIX || secrets.WORKING_DIRECTORY_PREFIX }}/${GITHUB_REPOSITORY}/${GITHUB_REF}"

        # Make sure the directory exists
        mkdir -p ${WORKING_DIRECTORY}
        echo "WORKING_DIRECTORY: ${WORKING_DIRECTORY}"

        # Set as default working directory for following steps
        echo "WORKING_DIRECTORY=${WORKING_DIRECTORY}" >> $GITHUB_ENV
