name: 'Setup Working Directory'
description: 'Sets up the working directory for the job'

runs:
  using: 'composite'
  steps:
    - id: set_working_directory
      shell: bash
      run: |
        if [[ -n "${GITHUB_HEAD_REF}" ]]; then
          WORKING_DIRECTORY="${GITHUB_WORKSPACE}/${GITHUB_HEAD_REF}"
        else
          WORKING_DIRECTORY="${GITHUB_WORKSPACE}"
        fi

        # Make sure the directory exists
        mkdir -p ${WORKING_DIRECTORY}
        echo "WORKING_DIRECTORY: ${WORKING_DIRECTORY}"
        cd $WORKING_DIRECTORY

        # Set as default working directory for following steps
        echo "WORKING_DIRECTORY=${WORKING_DIRECTORY}" >> $GITHUB_ENV
