name: 'Setup Working Directory'
description: 'Sets up the working directory for the job'

inputs:
  path:
    description: 'Path where the working directory should be created'
    default: ''
    required: false
  branch:
    description: 'Branch name to use in the working directory path (defaults to GITHUB_REF if not provided)'
    default: ''
    required: false

runs:
  using: 'composite'
  steps:
    - id: set_working_directory
      shell: bash
      run: |
        # Use the branch input if provided, otherwise fallback to GITHUB_REF
        BRANCH_NAME="${{ inputs.branch || env.GITHUB_REF }}"
        WORKING_DIRECTORY="${{ inputs.path || env.WORKING_DIRECTORY_PREFIX }}/${GITHUB_REPOSITORY}/branches/${BRANCH_NAME}"

        # Make sure the directory exists
        mkdir -p ${WORKING_DIRECTORY}
        echo "WORKING_DIRECTORY: ${WORKING_DIRECTORY}"

        # Set as default working directory for following steps
        echo "WORKING_DIRECTORY=${WORKING_DIRECTORY}" >> $GITHUB_ENV
