name: 'Setup Working Directory'
description: 'Sets up the working directory for the job'

inputs:
  path:
    description: 'Path where the working directory should be created'
    default: ''
    required: false

outputs:
  working-directory:
    description: 'The configured working directory path'

runs:
  using: 'node16'
  main: 'dist/index.js'