name: 'Setup Working Directory'
description: 'Sets up the working directory for the job'

inputs:
  PATH:
    description: 'Path where the working directory should be created'
    default: ''
    required: false
  BRANCH_NAME:
    description: 'Branch name to use in the working directory path (defaults to GITHUB_REF if not provided)'
    default: ''
    required: false

outputs:
  workingDirectory:
    description: 'The generated working directory'
    value:  ${{ steps.set-working-directory.outputs.workingDirectory }}

runs:
  using: 'composite'
  steps:
    - id: set-working-directory
      shell: bash
      run: |
        # Use the branch input if provided, otherwise fallback to GITHUB_REF
        BRANCH_NAME="${{ inputs.BRANCH_NAME || env.BRANCH_NAME }}"

        if [[ -z "$BRANCH_NAME" ]]; then
          echo "No branch name provided, using GITHUB_REF: $GITHUB_REF"
          BRANCH_NAME=$GITHUB_REF
        else
          BRANCH_NAME="refs/heads/${BRANCH_NAME}"
        fi

        # Sanitize workflow name for filesystem compatibility
        WORKFLOW_NAME="${{ github.workflow }}"
        WORKFLOW_NAME=$(echo "$WORKFLOW_NAME" | sed 's/[^a-zA-Z0-9._-]/_/g' | tr '[:upper:]' '[:lower:]')

        # Create working directory with separated prefix and branch structure
        WORKING_DIRECTORY="${{ inputs.PATH || env.WORKING_DIRECTORY_PREFIX }}/${GITHUB_REPOSITORY}/${WORKFLOW_NAME}/${BRANCH_NAME}"


        # Make sure the directory exists
        mkdir -p ${WORKING_DIRECTORY}
        echo "Original Branch Name: ${BRANCH_NAME}"
        echo "WORKING_DIRECTORY: ${WORKING_DIRECTORY}"

        # Set as default working directory for following steps
        echo "WORKING_DIRECTORY=${WORKING_DIRECTORY}" >> "${GITHUB_ENV}"
        echo "workingDirectory=${WORKING_DIRECTORY}" >> "${GITHUB_OUTPUT}"
